const express = require('express');
const cors = require('cors');
const pool = require('./db');
pool.query('SELECT NOW()').then(r => console.log('DB OK:', r.rows[0])).catch(e => console.log('DB ERROR:', e.message));
const authRoutes = require('./auth');

console.log('DATABASE_URL:', process.env.DATABASE_URL);
console.log('DB_PASSWORD:', process.env.DB_PASSWORD);

const app = express();
app.use(cors({
  origin: [
    'http://localhost:5173',
    'https://symptomlens.vercel.app',
    'https://symptomlens-g6oozczy6-priyaanandan682-7674s-projects.vercel.app'
  ],
  credentials: true
}));
app.use(express.json());

app.use('/auth', authRoutes);

app.get('/', (req, res) => {
  res.json({ message: 'SymptomLens API is running!' });
});

app.post('/symptoms', async (req, res) => {
  try {
    const { user_id, symptom_name, severity, notes } = req.body;
    const result = await pool.query(
      'INSERT INTO symptoms (user_id, symptom_name, severity, notes) VALUES ($1, $2, $3, $4) RETURNING *',
      [user_id, symptom_name, severity, notes]
    );
    res.json(result.rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/symptoms', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM symptoms ORDER BY logged_at DESC'
    );
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/checkins', async (req, res) => {
  try {
    const { user_id, sleep_hours, stress_level, mood } = req.body;
    const result = await pool.query(
      'INSERT INTO checkins (user_id, sleep_hours, stress_level, mood) VALUES ($1, $2, $3, $4) RETURNING *',
      [user_id, sleep_hours, stress_level, mood]
    );
    res.json(result.rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/checkins', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM checkins ORDER BY checked_in_at DESC'
    );
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/report/:userId', async (req, res) => {
  try {
    const PDFDocument = require('pdfkit');
    const { userId } = req.params;
    const symptomsResult = await pool.query(
      'SELECT * FROM symptoms WHERE user_id = $1 ORDER BY logged_at DESC LIMIT 20',
      [userId]
    );
    const userResult = await pool.query(
      'SELECT name, email FROM users WHERE id = $1',
      [userId]
    );
    const symptoms = symptomsResult.rows;
    const user = userResult.rows[0];
    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=symptom-report.pdf');
    doc.pipe(res);
    doc.fontSize(24).fillColor('#667eea').text('SymptomLens', { align: 'center' });
    doc.fontSize(14).fillColor('#333').text('Medical Symptom Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).fillColor('#666').text('Generated: ' + new Date().toLocaleDateString(), { align: 'center' });
    doc.moveDown();
    doc.fontSize(16).fillColor('#333').text('Patient Information');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#444').text('Name: ' + (user ? user.name : 'Unknown'));
    doc.text('Email: ' + (user ? user.email : 'Unknown'));
    doc.moveDown();
    doc.fontSize(16).fillColor('#333').text('Symptom History');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    if (symptoms.length === 0) {
      doc.fontSize(12).fillColor('#666').text('No symptoms logged yet.');
    } else {
      symptoms.forEach((s) => {
        const color = s.severity >= 7 ? '#F44336' : s.severity >= 4 ? '#FF9800' : '#4CAF50';
        doc.fontSize(13).fillColor('#333').text(s.symptom_name.toUpperCase(), { continued: true });
        doc.fontSize(12).fillColor(color).text('  Severity: ' + s.severity + '/10');
        doc.fontSize(11).fillColor('#666').text('Date: ' + new Date(s.logged_at).toLocaleString());
        if (s.notes) doc.text('Notes: ' + s.notes);
        doc.moveDown(0.5);
      });
    }
    doc.moveDown();
    doc.fontSize(16).fillColor('#333').text('Summary');
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    const avgSeverity = symptoms.length > 0
      ? (symptoms.reduce((a, b) => a + b.severity, 0) / symptoms.length).toFixed(1)
      : 0;
    doc.fontSize(12).fillColor('#444').text('Total symptoms logged: ' + symptoms.length);
    doc.text('Average severity: ' + avgSeverity + '/10');
    doc.moveDown();
    doc.fontSize(11).fillColor('#888').text('This report was generated by SymptomLens. Please share with your doctor.', { align: 'center' });
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});